### ISSUE TITLE
Unnecessary blocking of buecher.de

### ISSUE THREAD

**Issue by head1328** [autinerd/anti-axelspringer-hosts#13]
According to some news sources, Axel Springer no longer has any shares in buecher.de.

https://de.wikipedia.org/wiki/Buecher.de#Gesellschafter
https://www.axelspringer.com/de/presseinformationen/axel-springer-verkauft-seine-buecher-de-anteile-an-weltbild

**Comment by autinerd** [comment]
Thanks!
