### ISSUE TITLE
question: What makes Axel Springer websites so bad?

### ISSUE THREAD

**Issue by T145** [autinerd/anti-axelspringer-hosts#19]
I'm just curious as to why this organization requires blocking.

**Comment by nichu42** [comment]
@T145: The following NYT article should give you an idea why one might want to block content from this media company: https://www.nytimes.com/2021/10/17/business/media/axel-springer-bild-julian-reichelt.html

**Comment by T145** [comment]
Seems like Mr. Reichelt was dismissed temporarily and later reinstated: https://www.nytimes.com/2021/10/18/business/media/julian-reichelt-axel-springer.html

Which was also covered in an Axel Springer blog post: https://www.axelspringer.com/en/ax-press-release/following-new-findings-axel-springer-relieves-julian-reichelt-of-his-duties

Keep up the good work!
