### ISSUE TITLE
Upday

### ISSUE THREAD

**Issue by Zoey2936** [autinerd/anti-axelspringer-hosts#20]
https://de.wikipedia.org/wiki/Upday
I think Upday is missing in the Block lists

**Comment by Zoey2936** [comment]
After looking some other sites from: https://www.axelspringer.com/de/marken
Here some sites, that worked:
- good.co
- immoweb.de
- logic-immo.com
- saongroup.com
- autobazar.eu
- hobbyconsolas.com
- insider.com
- insider-inc.com
- insiderintelligence.com
- blau-international.com
- diedame.de
- fitbook.de
- computerhoy.com

**Comment by autinerd** [comment]
Thank you very much!
