### ISSUE TITLE
Some more hosts

### ISSUE THREAD

**Issue by Zoey2936** [autinerd/anti-axelspringer-hosts#21]
- www.asideas.de
- asideas.de
- prod.yana.asideas.de
- img.yana.asideas.de
- www.ideas-engineering.io
- ideas-engineering.io
- gamification.upday.com

These are some websites and apis of upday on samsung phones

**Comment by Zoey2936** [comment]
@autinerd ?

**Comment by autinerd** [comment]
@Zoey2936 thank for reminding me!
