### ISSUE TITLE
"Insider Inc. is a subsidiary of Axel Springer SE."

### ISSUE THREAD

**Issue by pgeorgi** [autinerd/anti-axelspringer-hosts#22]
Taken from https://www.businessinsider.com/contact: "Insider Inc. is a subsidiary of Axel Springer SE."

Some of its other domains (insider-inc.com, insider.com) are already on the list, but while digging I found a few that are missing:

businessinsider.com (but not africa.businessinsider.com), businessinsider.es, businessinsider.com.pl (Ringier Axel Springer Polska joint venture), businessinsider.co.za, topgear.es, businessinsider.mx

**Comment by Benedikt81** [comment]
More information about the acquisition which happened in 2015: https://de.wikipedia.org/wiki/Business_Insider

**Comment by autinerd** [comment]
Thanks, I added the missing Business Insider sites (some were already there)
