### ISSUE TITLE
AS scheinbar nicht mehr bei RS2 involviert

### ISSUE THREAD

**Issue by heimchemiker** [autinerd/anti-axelspringer-hosts#5]
Zitat Issue bei TobsA13/ASB (https://github.com/TobsA13/ASB/issues/7)
"Seit 2014 ist der Axel-Springer-Verlag nicht mehr Teilhaber an der Regiocast.

https://www.horizont.net/medien/nachrichten/Privatradio-Axel-Springer-steigt-bei-Regiocast-aus-118937

rs2.de kann also wahrscheinlich entfernt werden. [...]"

Vor dem Gedanken der Transparenz und Nachvollziehbarkeit: Gibts zu den Involvierungen Quellen?

**Comment by autinerd** [comment]
Danke sehr!

Die meisten Involvierungen sind von axelspringer.com entnommen, oder auf den Seiten selber einsehbar.
